version: '3.3'
services:
  web:
    image: nginx:1.13-alpine
    ports:
        - "80:80"
        - "443:443"
    volumes:
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - ./:/code
    links:
        - django
  django:
    build:
      context: .
      args:
        - REQUIREMENTS=production.txt
    command: uwsgi --ini=run/uwsgi.ini
